services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: springboot-webapp-image:latest
    container_name: springboot-webapp
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - maven-repo:/root/.m2  # Adiciona o volume para o repositório Maven
    environment:
      - JAVA_OPTS=-Xmx512m

volumes:
  maven-repo: 
